In [1]:
pip install pandas

Requirement already satisfied: pandas in d:\python interpreter\python\python313\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in d:\python interpreter\python\python313\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sadi\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\python interpreter\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\sadi\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
pd.set_option('display.max_columns', 12) 
pd.set_option('display.max_rows', 15)

In [4]:
df = pd.read_csv("diamonds.csv") # 'https://github.com/Md-Siam07/dataset/blob/main/diamonds.csv'
# df = pd.read_csv('https://raw.githubusercontent.com/Md-Siam07/dataset/main/diamonds.csv')

In [5]:
df.head()

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

**Read from web source**

In [6]:
pip install lxml

Requirement already satisfied: lxml in d:\python interpreter\python\python313\lib\site-packages (6.1.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
df_list = pd.read_html("https://www.w3schools.com/html/html_tables.asp")

print(df_list)
print(type(df_list)) # This will show that df_list is a list of DataFrames

[                        Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy,           Tag                                        Description
0     <table>                                    Defines a table
1        <th>                   Defines a header cell in a table
2        <tr>                           Defines a row in a table
3        <td>                          Defines a cell in a table
4   <caption>                            Defines a table caption
5  <colgroup>  Specifies a group of one or more columns in a ...
6       <col>  Specifies column properties for each column wi...
7     <thead>               Groups the header content in a table
8     <tbody>                 Groups the body content in a table
9     <tfoot>               Groups the footer content in a table]
<class 'list'>

In [8]:
df_list[1]

          Tag                                        Description
0     <table>                                    Defines a table
1        <th>                   Defines a header cell in a table
2        <tr>                           Defines a row in a table
3        <td>                          Defines a cell in a table
4   <caption>                            Defines a table caption
5  <colgroup>  Specifies a group of one or more columns in a ...
6       <col>  Specifies column properties for each column wi...
7     <thead>               Groups the header content in a table
8     <tbody>                 Groups the body content in a table
9     <tfoot>               Groups the footer content in a table

In [9]:
df.head()

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [10]:
# Display the first 8 rows
df.head(8)

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
5,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48
6,7,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47
7,8,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53

In [11]:
# Display the last 5 rows (default)
df.tail()

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [12]:
# Display the last 12 rows
df.tail(12)

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
53928,53929,0.79,Premium,E,SI2,61.4,58.0,2756,6.03,5.96,3.68
53929,53930,0.71,Ideal,G,VS1,61.4,56.0,2756,5.76,5.73,3.53
53930,53931,0.71,Premium,E,SI1,60.5,55.0,2756,5.79,5.74,3.49
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43
53932,53933,0.70,Very Good,E,VS2,60.5,59.0,2757,5.71,5.76,3.47
53933,53934,0.70,Very Good,E,VS2,61.2,59.0,2757,5.69,5.72,3.49
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [13]:
df.shape

(53940, 11)

In [14]:
print(df.columns)

Index(['rownames', 'carat', 'cut', 'color', 'clarity', 'depth', 'table',
       'price', 'x', 'y', 'z'],
      dtype='str')

In [15]:
listed_columns = df.columns.to_list()
listed_columns

['rownames',
 'carat',
 'cut',
 'color',
 'clarity',
 'depth',
 'table',
 'price',
 'x',
 'y',
 'z']

In [16]:
# Get data types for each column
df.dtypes

rownames      int64
carat       float64
cut             str
color           str
clarity         str
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  53940 non-null  int64
 1   carat     53940 non-null  float64
 2   cut       53940 non-null  str
 3   color     53940 non-null  str
 4   clarity   53940 non-null  str
 5   depth     53940 non-null  float64
 6   table     53940 non-null  float64
 7   price     53940 non-null  int64
 8   x         53940 non-null  float64
 9   y         53940 non-null  float64
 10  z         53940 non-null  float64
dtypes: float64(6), int64(2), str(3)
memory usage: 4.5 MB

In [18]:
df.describe()

,rownames,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,26970.500000,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,15571.281097,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,1.000000,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,13485.750000,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,26970.500000,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,40455.250000,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,53940.000000,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [19]:
# Include all columns (including non-numeric)
df.describe(include='all')

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940,53940,53940,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
unique,NaN,NaN,5,7,8,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Ideal,G,SI1,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,21551,11292,13065,NaN,NaN,NaN,NaN,NaN,NaN
mean,26970.500000,0.797940,NaN,NaN,NaN,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,15571.281097,0.474011,NaN,NaN,NaN,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,1.000000,0.200000,NaN,NaN,NaN,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,13485.750000,0.400000,NaN,NaN,NaN,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,26970.500000,0.700000,NaN,NaN,NaN,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,40455.250000,1.040000,NaN,NaN,NaN,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,53940.000000,5.010000,NaN,NaN,NaN,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [20]:
# Transpose for better readability
df.describe().T

,count,mean,std,min,25%,50%,75%,max
rownames,53940.0,26970.500000,15571.281097,1.0,13485.75,26970.50,40455.25,53940.00
carat,53940.0,0.797940,0.474011,0.2,0.40,0.70,1.04,5.01
depth,53940.0,61.749405,1.432621,43.0,61.00,61.80,62.50,79.00
table,53940.0,57.457184,2.234491,43.0,56.00,57.00,59.00,95.00
price,53940.0,3932.799722,3989.439738,326.0,950.00,2401.00,5324.25,18823.00
x,53940.0,5.731157,1.121761,0.0,4.71,5.70,6.54,10.74
y,53940.0,5.734526,1.142135,0.0,4.72,5.71,6.54,58.90
z,53940.0,3.538734,0.705699,0.0,2.91,3.53,4.04,31.80

In [21]:
# Custom percentiles
df.describe(percentiles=[.33, .66, .90])

,rownames,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,26970.500000,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,15571.281097,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,1.000000,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
33%,17800.870000,0.500000,61.300000,56.000000,1228.000000,5.030000,5.030000,3.100000
66%,35600.740000,1.000000,62.300000,58.000000,4221.000000,6.330000,6.330000,3.910000
90%,48546.100000,1.510000,63.300000,60.000000,9821.000000,7.310000,7.300000,4.520000
max,53940.000000,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [22]:
pip install openpyxl

Requirement already satisfied: openpyxl in d:\python interpreter\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in d:\python interpreter\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
df.to_csv('output.csv', index=False)

In [35]:
# Save to Excel
df.to_excel('output_index_false.xlsx', index=False)

df.to_excel('output_index_true.xlsx', index=True)

In [ ]:
# Save to HTML
df.to_html('output.html')

In [34]:
# Save to JSON
df.head(10).to_json('output.json')

# Save the first 10 rows in a clean, human-readable JSON format
df.head(10).to_json('output_10.json', orient='records', indent=4)

In [26]:
# df = pd.read_csv('input.csv')

# Save to Excel
# df.to_excel('output.xlsx', index=False)

**Common Data Inspection Patterns**

In [27]:
# Step 1: Load the data
df = pd.read_json('output.json')

# Step 2: Quick overview
print(f"Dataset shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")

# Step 3: Examine first few rows
df.head()

# Step 4: Check data types and missing values
df.info()

# Step 5: Statistical summary
df.describe(include='all')

# Step 6: Check for duplicates
print(f"Duplicate rows: {df.duplicated().sum()}")

Dataset shape: (53940, 11)
Columns: ['rownames', 'carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y', 'z']
<class 'pandas.DataFrame'>
Index: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  53940 non-null  int64
 1   carat     53940 non-null  float64
 2   cut       53940 non-null  str
 3   color     53940 non-null  str
 4   clarity   53940 non-null  str
 5   depth     53940 non-null  float64
 6   table     53940 non-null  float64
 7   price     53940 non-null  int64
 8   x         53940 non-null  float64
 9   y         53940 non-null  float64
 10  z         53940 non-null  float64
dtypes: float64(6), int64(2), str(3)
memory usage: 4.9 MB
Duplicate rows: 0

In [28]:
#Exercise 1
df = pd.read_csv('https://raw.githubusercontent.com/Md-Siam07/dataset/main/diamonds.csv')
df.head()

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [29]:
#Exercise 2
(rows, columns) = df.shape
print(f'number of rows {rows}')
print(f'number of columns {columns}')

number of rows 53940
number of columns 11

In [30]:
#Exercise 3
df.tail(7)

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
53933,53934,0.70,Very Good,E,VS2,61.2,59.0,2757,5.69,5.72,3.49
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [31]:
#Exercise 4
print(f"Columns: {df.columns.tolist()}")

Columns: ['rownames', 'carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y', 'z']

In [32]:
#Exercise 5
df.dtypes

rownames      int64
carat       float64
cut             str
color           str
clarity         str
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [33]:
#Exercise 6 & 7
df.describe(include='all')

,rownames,carat,cut,color,clarity,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940,53940,53940,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
unique,NaN,NaN,5,7,8,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Ideal,G,SI1,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,21551,11292,13065,NaN,NaN,NaN,NaN,NaN,NaN
mean,26970.500000,0.797940,NaN,NaN,NaN,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,15571.281097,0.474011,NaN,NaN,NaN,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,1.000000,0.200000,NaN,NaN,NaN,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,13485.750000,0.400000,NaN,NaN,NaN,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,26970.500000,0.700000,NaN,NaN,NaN,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,40455.250000,1.040000,NaN,NaN,NaN,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,53940.000000,5.010000,NaN,NaN,NaN,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000